name: Get Feed

on:
  schedule:
    - cron: '30 14,2 * * *' # 2:30pm & 2:30am UCT
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 43200 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
  update-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 43200 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Update Notion Feed
        run: npm run feed

  update-feed2:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 43200 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Update Notion Feed
        run: npm run feed
