name: Get Feed

on:
  schedule:
    - cron: '30 14,2 * * *' # 2:30pm & 2:30am UCT
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
      LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
      LANGFUSE_HOST: ${{ secrets.LANGFUSE_HOST }}
      RUN_FREQUENCY: 604800 # in seconds
    steps:
      - uses: actions/checkout@v4 # Use the latest checkout action[2][6]

      - uses: actions/setup-node@v4 # Use the latest setup-node action[6]
        with:
          node-version: '20.x' # Specify Node.js 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Update Notion Feed
        run: npm run feed
